"""First-principles research runtime kernel.

This package is intentionally independent from the historical LangGraph
implementation. It defines the domain objects and execution boundary that new
product features should target: run specs, stage specs, artifacts, validators,
events, and deterministic runtime context.
"""

from .engine import ResearchKernel
from .models import (
    ArtifactRecord,
    ArtifactSpec,
    BudgetExceededError,
    BudgetLedger,
    BudgetPolicy,
    CampaignExecutionSpec,
    CheckpointStore,
    CouncilPolicy,
    DecisionQueue,
    DecisionRecord,
    EvidenceLink,
    EventRecord,
    FailurePolicy,
    FeatureFlagRoute,
    GraphSpec,
    GraphTemplateSpec,
    HumanDecisionRequiredError,
    InputSpec,
    InMemoryEventBus,
    JsonlEventBus,
    ModelPolicy,
    ModelPolicyError,
    ModelRegistry,
    ModelSpec,
    RetryPolicy,
    RouteCondition,
    RouteSpec,
    RouterSpec,
    RunCheckpoint,
    RunSpec,
    RuntimeContext,
    SchemaRegistry,
    SchemaValidationError,
    SpendRecord,
    StateFieldContract,
    StageAdapterRegistry,
    StageAdapterSpec,
    StageOutcome,
    StageSpec,
    SubgraphSpec,
    ToolPolicyError,
    ToolRegistry,
    ToolSpec,
    ValidationResult,
    ValidatorRegistry,
)
from .read_models import (
    KernelArtifactReadModel,
    KernelRunReadModel,
    KernelStageReadModel,
    project_run,
    read_jsonl_events,
)
from .native_research import (
    KERNEL_NATIVE_STAGE_IDS,
    KERNEL_NATIVE_SCAFFOLD_STAGE_IDS,
    build_kernel_native_research_kernel,
    register_kernel_native_adapters,
)

__all__ = [
    "ArtifactRecord",
    "ArtifactSpec",
    "BudgetExceededError",
    "BudgetLedger",
    "BudgetPolicy",
    "CampaignExecutionSpec",
    "CheckpointStore",
    "CouncilPolicy",
    "DecisionQueue",
    "DecisionRecord",
    "EvidenceLink",
    "EventRecord",
    "FailurePolicy",
    "FeatureFlagRoute",
    "GraphSpec",
    "GraphTemplateSpec",
    "HumanDecisionRequiredError",
    "InputSpec",
    "InMemoryEventBus",
    "JsonlEventBus",
    "ModelPolicy",
    "ModelPolicyError",
    "ModelRegistry",
    "ModelSpec",
    "ResearchKernel",
    "RetryPolicy",
    "RouteCondition",
    "RouteSpec",
    "RouterSpec",
    "RunCheckpoint",
    "RunSpec",
    "RuntimeContext",
    "SchemaRegistry",
    "SchemaValidationError",
    "SpendRecord",
    "StateFieldContract",
    "StageAdapterRegistry",
    "StageAdapterSpec",
    "StageOutcome",
    "StageSpec",
    "SubgraphSpec",
    "ToolPolicyError",
    "ToolRegistry",
    "ToolSpec",
    "ValidationResult",
    "ValidatorRegistry",
    "KernelArtifactReadModel",
    "KernelRunReadModel",
    "KernelStageReadModel",
    "KERNEL_NATIVE_STAGE_IDS",
    "KERNEL_NATIVE_SCAFFOLD_STAGE_IDS",
    "build_kernel_native_research_kernel",
    "project_run",
    "read_jsonl_events",
    "register_kernel_native_adapters",
]
