"""Diagnostic source contracts derived from the original research engine.

These definitions preserve node ids, routes, and artifact hints from the
original graph as structured SDK data. They are source material for the
SDK-native target graph, not an execution authority.
"""

from __future__ import annotations

from msc_sdk.stage_contracts import ArtifactContract, BudgetPolicy, RouteContract, StageContract


def a(path: str, kind: str = "markdown", *, required: bool = True, description: str = "", legacy: tuple[str, ...] = ()) -> ArtifactContract:
    return ArtifactContract(path=path, kind=kind, required=required, description=description, legacy_paths=legacy)


def r(target: str, kind: str = "stage_order", *, condition: str = "always", description: str = "") -> RouteContract:
    return RouteContract(target=target, kind=kind, condition=condition, description=description)


CONTROL_BUDGET = BudgetPolicy(relative_weight=0, spend=False, notes="control node; no direct model spend")
AGENT_BUDGET = BudgetPolicy(relative_weight=1, spend=True)
HEAVY_AGENT_BUDGET = BudgetPolicy(relative_weight=2, spend=True, notes="usually higher-token or multi-agent work")
TRACK_BUDGET = BudgetPolicy(relative_weight=1, spend=True, notes="track wrapper may invoke a subgraph")

DEFAULT_FAILURE = "stop_and_await_human_feedback"
RETRY_FAILURE = "emit_failure_and_request_rewrite_or_rerun"
GATE_FAILURE = "emit_approval_or_recovery_request"


CONTRACTS: tuple[StageContract, ...] = (
    StageContract(
        id="persona_council",
        title="Persona Council",
        kind="agent",
        purpose="Frame the research task through multiple expert personas, debate assumptions, and synthesize the initial research posture.",
        inputs=("objective",),
        required_artifacts=(
            a("artifacts/persona_debate.md", description="Persona debate transcript and competing perspectives.", legacy=("paper_workspace/persona_council.md",)),
            a("artifacts/research_proposal.md", description="Initial synthesized research proposal.", legacy=("paper_workspace/research_proposal.md",)),
        ),
        optional_artifacts=(a("artifacts/persona_votes.json", "json", required=False),),
        validators=("proposal_not_empty", "personas_reached_synthesis"),
        tool_families=("llm", "persona_council", "budget_tracker"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("after_persona_debate_framing",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("literature_review_agent"),),
        diagnostic_runtime_mapping={"module": "consortium.persona_council", "builder": "create_persona_council_node"},
    ),
    StageContract(
        id="literature_review_agent",
        title="Literature Review",
        kind="agent",
        purpose="Search, read, and organize related work; decide whether the proposed direction is feasible and novel enough to continue.",
        inputs=("persona_council", "objective"),
        required_artifacts=(
            a("artifacts/literature_matrix.md", description="Related-work matrix and citations.", legacy=("paper_workspace/literature_review.md",)),
            a("artifacts/lit_review_feasibility.json", "json", description="Feasibility and novelty decision.", legacy=("paper_workspace/lit_review_feasibility.json",)),
        ),
        optional_artifacts=(a("artifacts/source_bibliography.bib", "bib", required=False),),
        validators=("citations_present", "feasibility_json_schema"),
        tool_families=("paper_search", "arxiv", "web", "llm"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("after_literature_feasibility",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("lit_review_gate"),),
        diagnostic_runtime_mapping={"builder": "build_literature_review_node"},
    ),
    StageContract(
        id="lit_review_gate",
        title="Literature Feasibility Gate",
        kind="gate",
        purpose="Route infeasible or weakly grounded ideas back to framing; otherwise continue to brainstorm concrete approaches.",
        inputs=("literature_review_agent",),
        required_artifacts=(a("artifacts/lit_review_gate_decision.json", "json", description="Feasibility routing decision."),),
        validators=("feasibility_decision_present",),
        tool_families=("artifact_validator",),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("on_infeasible_literature",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("persona_council", "loop", condition="infeasible", description="Reframe the project after failed literature feasibility."),
            r("brainstorm_agent", "route", condition="feasible"),
        ),
        diagnostic_runtime_mapping={"router": "lit_review_gate_router"},
    ),
    StageContract(
        id="brainstorm_agent",
        title="Brainstorm",
        kind="agent",
        purpose="Generate hypotheses, approach menus, and priority ordering for theory and empirical execution.",
        inputs=("lit_review_gate", "persona_council"),
        required_artifacts=(
            a("artifacts/brainstorm.md", description="Hypotheses and approach menu.", legacy=("paper_workspace/brainstorm.md",)),
            a("artifacts/approach_menu.json", "json", description="Structured approach options and priorities."),
        ),
        optional_artifacts=(a("artifacts/open_questions.md", required=False),),
        validators=("brainstorm_required_sections", "approach_menu_schema"),
        tool_families=("llm", "counsel"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("after_hypotheses_and_goals",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("brainstorm_artifact_gate"),),
        diagnostic_runtime_mapping={"builder": "build_brainstorm_node"},
    ),
    StageContract(
        id="brainstorm_artifact_gate",
        title="Brainstorm Artifact Gate",
        kind="gate",
        purpose="Validate that brainstorming produced enough structured material to formalize goals.",
        inputs=("brainstorm_agent",),
        required_artifacts=(a("artifacts/brainstorm_gate_decision.json", "json"),),
        validators=("brainstorm_artifact_contract",),
        tool_families=("artifact_validator",),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("on_brainstorm_artifact_failure",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("brainstorm_agent", "loop", condition="missing_or_invalid_artifacts"),
            r("formalize_goals_entry", "route", condition="valid"),
        ),
        diagnostic_runtime_mapping={"router": "brainstorm_artifact_gate_router"},
    ),
    StageContract(
        id="formalize_goals_entry",
        title="Formalize Goals Entry",
        kind="control",
        purpose="Prepare structured context for turning brainstormed approaches into measurable research goals.",
        inputs=("brainstorm_artifact_gate",),
        required_artifacts=(a("artifacts/formalize_goals_entry.json", "json"),),
        validators=("critical_failure_absent",),
        tool_families=("state_mapper",),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("formalize_goals_agent"),),
        diagnostic_runtime_mapping={"builder": "build_formalize_goals_entry_node"},
    ),
    StageContract(
        id="formalize_goals_agent",
        title="Formalize Goals",
        kind="agent",
        purpose="Convert ideas into explicit hypotheses, success criteria, track assignments, and measurable objectives.",
        inputs=("formalize_goals_entry",),
        required_artifacts=(
            a("artifacts/research_goals.json", "json", description="Structured goals, hypotheses, and success criteria.", legacy=("paper_workspace/research_goals.json",)),
            a("artifacts/goal_spec.md", description="Human-readable goal contract."),
        ),
        optional_artifacts=(a("artifacts/goal_risks.md", required=False),),
        validators=("research_goals_schema", "success_criteria_present"),
        tool_families=("llm", "json_schema"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_hypotheses_and_goals",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("research_plan_writeup_agent"),),
        diagnostic_runtime_mapping={"builder": "build_formalize_goals_node"},
    ),
    StageContract(
        id="research_plan_writeup_agent",
        title="Research Plan Writeup",
        kind="agent",
        purpose="Write the plan that a researcher can approve before costly execution tracks begin.",
        inputs=("formalize_goals_agent",),
        required_artifacts=(a("artifacts/research_plan.md", description="Execution plan and rationale.", legacy=("paper_workspace/research_plan.md",)),),
        optional_artifacts=(a("artifacts/planning_notes.md", required=False),),
        validators=("plan_mentions_goals", "plan_has_execution_steps"),
        tool_families=("llm", "markdown_writer"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_graph_planning",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("track_decomposition_gate"),),
        diagnostic_runtime_mapping={"builder": "build_research_plan_writeup_node"},
    ),
    StageContract(
        id="track_decomposition_gate",
        title="Track Decomposition Gate",
        kind="router",
        purpose="Split the plan into theory and empirical questions and decide which tracks should run.",
        inputs=("research_plan_writeup_agent",),
        required_artifacts=(a("artifacts/track_decomposition.json", "json", legacy=("paper_workspace/track_decomposition.json",)),),
        validators=("track_decomposition_schema",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("after_graph_planning",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("milestone_goals"),),
        diagnostic_runtime_mapping={"builder": "build_track_decomposition_gate_node"},
    ),
    StageContract(
        id="milestone_goals",
        title="Goals Approval Pause",
        kind="approval",
        purpose="Human checkpoint after goals and plan are known, before execution tracks consume meaningful budget.",
        inputs=("track_decomposition_gate",),
        required_artifacts=(a("artifacts/goals_approval.json", "json"),),
        validators=("human_decision_recorded_or_autonomous_policy",),
        tool_families=("human_review", "steering_http"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("before_real_spend", "after_graph_planning"),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("theory_track", "fanout", condition="math_enabled_and_theory_questions"),
            r("experiment_track", "fanout", condition="empirical_questions_or_default"),
        ),
        diagnostic_runtime_mapping={"builder": "build_milestone_gate_node", "milestone": "research_plan"},
    ),
    StageContract(
        id="theory_track",
        title="Theory Track",
        kind="track",
        purpose="Wrapper around the proof-oriented subgraph for theory questions.",
        inputs=("milestone_goals",),
        required_artifacts=(a("artifacts/theory_track_summary.md", legacy=("paper_workspace/theory_track_summary.md",)),),
        optional_artifacts=(a("artifacts/theory_failure_report.md", required=False),),
        validators=("theory_track_status_present",),
        tool_families=("langgraph_subgraph", "math_agents", "tree_search_optional"),
        budget_policy=TRACK_BUDGET,
        human_pause_policy=("before_theory_proof_escalation",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(
            r("math_literature_agent", "subgraph", condition="expanded_control_view"),
            r("track_merge", "fanin", condition="track_complete_or_skipped"),
        ),
        diagnostic_runtime_mapping={"builder": "build_track_subgraph_node", "status_key": "theory_track_status"},
    ),
    StageContract(
        id="math_literature_agent",
        title="Math Literature",
        kind="agent",
        purpose="Find mathematical prior art, lemmas, and proof strategies relevant to the theory questions.",
        inputs=("theory_track",),
        required_artifacts=(a("artifacts/math_literature.md", legacy=("paper_workspace/math_literature.md",)),),
        optional_artifacts=(a("artifacts/math_bibliography.bib", "bib", required=False),),
        validators=("math_sources_present",),
        tool_families=("paper_search", "arxiv", "llm"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("before_theory_proof_escalation",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("math_proposer_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_math_literature_node"},
    ),
    StageContract(
        id="math_proposer_agent",
        title="Math Proposer",
        kind="agent",
        purpose="Propose theorem statements, proof sketches, and dependency structure.",
        inputs=("math_literature_agent",),
        required_artifacts=(a("artifacts/theorem_proposals.md", legacy=("paper_workspace/theorem_proposals.md",)),),
        optional_artifacts=(a("artifacts/lemma_dependency_graph.json", "json", required=False),),
        validators=("theorem_proposals_nonempty",),
        tool_families=("llm", "math_reasoning"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("before_theory_proof_escalation",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("goal_tag_validation_gate", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_math_proposer_node"},
    ),
    StageContract(
        id="goal_tag_validation_gate",
        title="Goal Tag Validation Gate",
        kind="gate",
        purpose="Ensure proposed mathematical claims map back to approved research goals.",
        inputs=("math_proposer_agent",),
        required_artifacts=(a("artifacts/goal_tag_validation.json", "json"),),
        validators=("goal_tags_match_research_goals",),
        tool_families=("artifact_validator",),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("math_prover_agent", "subgraph"),),
        diagnostic_runtime_mapping={"node": "goal_tag_validation_gate"},
    ),
    StageContract(
        id="math_prover_agent",
        title="Math Prover",
        kind="agent",
        purpose="Attempt formal or semi-formal proofs for the selected claims.",
        inputs=("goal_tag_validation_gate",),
        required_artifacts=(a("artifacts/proof_attempt.md", legacy=("paper_workspace/proof_attempt.md",)),),
        optional_artifacts=(a("artifacts/proof_obstacles.md", required=False),),
        validators=("proof_attempt_present",),
        tool_families=("llm", "proof_reasoning", "python_optional"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("before_theory_proof_escalation",),
        failure_policy=RETRY_FAILURE,
        allowed_routes=(r("math_rigorous_verifier_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_math_prover_node"},
    ),
    StageContract(
        id="math_rigorous_verifier_agent",
        title="Math Rigorous Verifier",
        kind="agent",
        purpose="Check proofs adversarially for gaps, unstated assumptions, and invalid derivations.",
        inputs=("math_prover_agent",),
        required_artifacts=(a("artifacts/rigorous_verification.md", legacy=("paper_workspace/rigorous_verification.md",)),),
        optional_artifacts=(a("artifacts/proof_gap_report.json", "json", required=False),),
        validators=("verification_verdict_present",),
        tool_families=("llm", "adversarial_verification"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_theory_verification",),
        failure_policy=RETRY_FAILURE,
        allowed_routes=(r("human_review_gate", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_math_rigorous_verifier_node"},
    ),
    StageContract(
        id="human_review_gate",
        title="Human Theory Review Gate",
        kind="approval",
        purpose="Allow a researcher to accept, reject, or redirect the theory track before empirical verification.",
        inputs=("math_rigorous_verifier_agent",),
        required_artifacts=(a("artifacts/human_theory_review.json", "json"),),
        validators=("human_decision_recorded_or_autonomous_policy",),
        tool_families=("human_review", "steering_http"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("after_theory_verification",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("math_empirical_verifier_agent", "subgraph"),),
        diagnostic_runtime_mapping={"node": "human_review_gate"},
    ),
    StageContract(
        id="math_empirical_verifier_agent",
        title="Math Empirical Verifier",
        kind="agent",
        purpose="Use computational checks or toy examples to probe whether theory claims are plausible.",
        inputs=("human_review_gate",),
        required_artifacts=(a("artifacts/math_empirical_checks.md", legacy=("paper_workspace/math_empirical_checks.md",)),),
        optional_artifacts=(a("artifacts/math_check_results.json", "json", required=False),),
        validators=("empirical_check_summary_present",),
        tool_families=("python", "experiments", "llm"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_theory_verification",),
        failure_policy=RETRY_FAILURE,
        allowed_routes=(r("proof_transcription_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_math_empirical_verifier_node"},
    ),
    StageContract(
        id="proof_transcription_agent",
        title="Proof Transcription",
        kind="agent",
        purpose="Convert verified theory outputs into paper-ready proof text.",
        inputs=("math_empirical_verifier_agent",),
        required_artifacts=(a("artifacts/proof_section.md", legacy=("paper_workspace/proof_section.md",)),),
        optional_artifacts=(a("artifacts/proof_section.tex", "tex", required=False),),
        validators=("proof_text_ready_for_writeup",),
        tool_families=("llm", "latex"),
        budget_policy=AGENT_BUDGET,
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("theory_track_repair_gate", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_proof_transcription_node"},
    ),
    StageContract(
        id="theory_track_repair_gate",
        title="Theory Track Repair Gate",
        kind="gate",
        purpose="Decide whether the theory subgraph can finish, needs repair, or should stop for human feedback.",
        inputs=("proof_transcription_agent",),
        required_artifacts=(a("artifacts/theory_repair_decision.json", "json"),),
        validators=("repair_decision_present",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("before_repair_retry_loops", "on_every_failure"),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("math_proposer_agent", "loop", condition="repair_requested"),
            r("track_merge", "fanin", condition="theory_complete"),
        ),
        diagnostic_runtime_mapping={"node": "theory_track_repair_gate"},
    ),
    StageContract(
        id="experiment_track",
        title="Experiment Track",
        kind="track",
        purpose="Wrapper around the empirical subgraph for designing, running, verifying, and transcribing experiments.",
        inputs=("milestone_goals",),
        required_artifacts=(a("artifacts/experiment_track_summary.md", legacy=("paper_workspace/experiment_track_summary.md",)),),
        optional_artifacts=(a("artifacts/experiment_failure_report.md", required=False),),
        validators=("experiment_track_status_present",),
        tool_families=("langgraph_subgraph", "python", "experiments"),
        budget_policy=TRACK_BUDGET,
        human_pause_policy=("before_expensive_experiments",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(
            r("experiment_literature_agent", "subgraph", condition="expanded_control_view"),
            r("track_merge", "fanin", condition="track_complete_or_skipped"),
        ),
        diagnostic_runtime_mapping={"builder": "build_track_subgraph_node", "status_key": "experiment_track_status"},
    ),
    StageContract(
        id="experiment_literature_agent",
        title="Experiment Literature",
        kind="agent",
        purpose="Find datasets, baselines, metrics, and experimental methods relevant to the empirical questions.",
        inputs=("experiment_track",),
        required_artifacts=(a("artifacts/experiment_literature.md", legacy=("paper_workspace/experiment_literature.md",)),),
        optional_artifacts=(a("artifacts/experiment_bibliography.bib", "bib", required=False),),
        validators=("experiment_sources_present",),
        tool_families=("paper_search", "arxiv", "llm"),
        budget_policy=AGENT_BUDGET,
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("experiment_design_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_experiment_literature_node"},
    ),
    StageContract(
        id="experiment_design_agent",
        title="Experiment Design",
        kind="agent",
        purpose="Specify minimal experiments, baselines, metrics, and expected result tables.",
        inputs=("experiment_literature_agent",),
        required_artifacts=(a("artifacts/experiment_plan.md", legacy=("paper_workspace/experiment_plan.md", "paper_workspace/experiments_to_run_later.md")),),
        optional_artifacts=(a("artifacts/experiment_config.json", "json", required=False),),
        validators=("experiment_plan_present", "metrics_defined"),
        tool_families=("llm", "python_planning"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("before_expensive_experiments",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("experimentation_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_experiment_design_node"},
    ),
    StageContract(
        id="experimentation_agent",
        title="Experimentation",
        kind="agent",
        purpose="Implement and run local experiments, leaving reproducible code and raw results.",
        inputs=("experiment_design_agent",),
        required_artifacts=(
            a("artifacts/experiment_results.md", legacy=("paper_workspace/experiment_results.md",)),
            a("artifacts/experiment_manifest.json", "json"),
        ),
        optional_artifacts=(
            a("artifacts/experiment_code.py", "python", required=False),
            a("artifacts/figures.json", "json", required=False),
        ),
        validators=("results_present", "code_or_commands_recorded"),
        tool_families=("python", "local_subprocess", "filesystem"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("before_expensive_experiments",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("experiment_verification_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_experimentation_node"},
    ),
    StageContract(
        id="experiment_verification_agent",
        title="Experiment Verification",
        kind="agent",
        purpose="Check experiment code, metrics, and results for reproducibility and correctness.",
        inputs=("experimentation_agent",),
        required_artifacts=(a("artifacts/experiment_verification.md", legacy=("paper_workspace/experiment_verification.md",)),),
        optional_artifacts=(a("artifacts/verification_failures.json", "json", required=False),),
        validators=("verification_verdict_present",),
        tool_families=("python", "llm", "adversarial_verification"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_experiment_synthesis",),
        failure_policy=RETRY_FAILURE,
        allowed_routes=(r("experiment_transcription_agent", "subgraph"),),
        diagnostic_runtime_mapping={"builder": "build_experiment_verification_node"},
    ),
    StageContract(
        id="experiment_transcription_agent",
        title="Experiment Transcription",
        kind="agent",
        purpose="Turn verified empirical findings into paper-ready text, tables, and figure descriptions.",
        inputs=("experiment_verification_agent",),
        required_artifacts=(a("artifacts/experiment_section.md", legacy=("paper_workspace/experiment_section.md",)),),
        optional_artifacts=(a("artifacts/experiment_tables.md", required=False),),
        validators=("experiment_section_ready_for_writeup",),
        tool_families=("llm", "markdown_writer"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_experiment_synthesis",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("track_merge", "fanin"),),
        diagnostic_runtime_mapping={"builder": "build_experiment_transcription_node"},
    ),
    StageContract(
        id="track_merge",
        title="Track Merge",
        kind="control",
        purpose="Merge theory and experiment track outputs into one state for synthesis.",
        inputs=("theory_track", "experiment_track"),
        required_artifacts=(a("artifacts/track_merge_summary.md", legacy=("paper_workspace/track_merge_summary.md",)),),
        validators=("track_outputs_collected",),
        tool_families=("state_mapper",),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("verify_completion"),),
        diagnostic_runtime_mapping={"builder": "build_track_merge_node"},
    ),
    StageContract(
        id="verify_completion",
        title="Completion Verification",
        kind="router",
        purpose="Decide whether execution is sufficient, needs goal refinement, or requires a fundamental rethink.",
        inputs=("track_merge",),
        required_artifacts=(a("artifacts/completion_verification.json", "json", legacy=("paper_workspace/completion_verification.json",)),),
        validators=("completion_decision_present",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("after_experiment_synthesis", "on_every_failure"),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("formalize_results_agent", "route", condition="complete"),
            r("formalize_goals_agent", "loop", condition="needs_goal_refinement"),
            r("brainstorm_agent", "loop", condition="needs_fundamental_rethink"),
        ),
        diagnostic_runtime_mapping={"router": "verify_completion_router"},
    ),
    StageContract(
        id="formalize_results_agent",
        title="Formalize Results",
        kind="agent",
        purpose="Synthesize theory and experiment outcomes into claims, limitations, and paper-ready result narratives.",
        inputs=("verify_completion",),
        required_artifacts=(a("artifacts/formalized_results.md", legacy=("paper_workspace/formalized_results.md",)),),
        optional_artifacts=(a("artifacts/claims_and_limitations.json", "json", required=False),),
        validators=("claims_tied_to_evidence",),
        tool_families=("llm", "markdown_writer"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_experiment_synthesis",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("duality_check"),),
        diagnostic_runtime_mapping={"builder": "build_formalize_results_node"},
    ),
    StageContract(
        id="duality_check",
        title="Duality Check",
        kind="agent",
        purpose="Critique whether theory and empirical claims support each other or reveal a contradiction.",
        inputs=("formalize_results_agent",),
        required_artifacts=(a("artifacts/duality_check.json", "json", legacy=("paper_workspace/duality_check.json",)),),
        validators=("duality_verdict_present",),
        tool_families=("llm", "adversarial_verification"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("after_experiment_synthesis",),
        failure_policy=RETRY_FAILURE,
        allowed_routes=(r("duality_gate"),),
        diagnostic_runtime_mapping={"builder": "create_duality_check_node"},
    ),
    StageContract(
        id="duality_gate",
        title="Duality Gate",
        kind="gate",
        purpose="Route after duality critique: continue to paper production or gather follow-up literature and rethink.",
        inputs=("duality_check",),
        required_artifacts=(a("artifacts/duality_gate_decision.json", "json"),),
        validators=("duality_route_present",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("on_every_failure",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("resource_preparation_agent", "route", condition="pass"),
            r("followup_lit_review", "loop", condition="needs_followup_lit_review"),
        ),
        diagnostic_runtime_mapping={"router": "duality_gate_router"},
    ),
    StageContract(
        id="followup_lit_review",
        title="Follow-Up Literature Review",
        kind="agent",
        purpose="Resolve duality or novelty concerns by searching for targeted prior work before re-brainstorming.",
        inputs=("duality_gate",),
        required_artifacts=(a("artifacts/followup_literature.md", legacy=("paper_workspace/followup_literature.md",)),),
        validators=("followup_findings_present",),
        tool_families=("paper_search", "arxiv", "llm"),
        budget_policy=AGENT_BUDGET,
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("brainstorm_agent", "loop"),),
        diagnostic_runtime_mapping={"builder": "build_followup_lit_review_node"},
    ),
    StageContract(
        id="resource_preparation_agent",
        title="Resource Preparation",
        kind="agent",
        purpose="Prepare figures, tables, citations, and workspace resources for writing.",
        inputs=("duality_gate", "formalize_results_agent"),
        required_artifacts=(a("artifacts/resource_manifest.json", "json", legacy=("paper_workspace/resource_manifest.json",)),),
        optional_artifacts=(a("artifacts/figure_table_plan.md", required=False),),
        validators=("resource_manifest_schema",),
        tool_families=("filesystem", "llm", "citation_tools"),
        budget_policy=AGENT_BUDGET,
        human_pause_policy=("before_writeup",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("paper_contract_builder"),),
        diagnostic_runtime_mapping={"builder": "build_resource_preparation_node"},
    ),
    StageContract(
        id="paper_contract_builder",
        title="Paper Contract Builder",
        kind="control",
        purpose="Write the paper artifact contract that downstream writing and validation must satisfy.",
        inputs=("resource_preparation_agent",),
        required_artifacts=(a("artifacts/paper_contract.json", "json", legacy=("paper_workspace/paper_contract.json",)),),
        validators=("paper_contract_schema",),
        tool_families=("artifact_contract", "filesystem"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("before_writeup",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("writeup_agent"),),
        diagnostic_runtime_mapping={"builder": "build_paper_contract_node"},
    ),
    StageContract(
        id="writeup_agent",
        title="Writeup",
        kind="agent",
        purpose="Compose the paper-like artifact from validated research outputs.",
        inputs=("paper_contract_builder",),
        required_artifacts=(a("artifacts/final_paper.md", description="Primary paper draft.", legacy=("paper_workspace/final_paper.md",)),),
        optional_artifacts=(
            a("artifacts/final_paper.tex", "tex", required=False, legacy=("paper_workspace/final_paper.tex",)),
            a("artifacts/final_paper.pdf", "pdf", required=False, legacy=("paper_workspace/final_paper.pdf",)),
        ),
        validators=("paper_contract_terms_present", "required_sections_present"),
        tool_families=("llm", "markdown_writer", "latex_optional"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("before_writeup",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("writeup_artifact_gate"),),
        diagnostic_runtime_mapping={"builder": "build_writeup_node"},
    ),
    StageContract(
        id="writeup_artifact_gate",
        title="Writeup Artifact Gate",
        kind="gate",
        purpose="Ensure paper artifacts exist and meet required term/format contracts before proofreading.",
        inputs=("writeup_agent",),
        required_artifacts=(a("artifacts/writeup_gate_decision.json", "json"),),
        validators=("missing_writeup_artifacts", "required_terms"),
        tool_families=("artifact_validator", "latex_optional"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("on_every_failure",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("writeup_agent", "loop", condition="missing_or_invalid_paper_artifacts"),
            r("proofreading_entry", "route", condition="valid"),
        ),
        diagnostic_runtime_mapping={"router": "writeup_artifact_gate_router"},
    ),
    StageContract(
        id="proofreading_entry",
        title="Proofreading Entry",
        kind="control",
        purpose="Prepare the current paper draft and instructions for copyediting.",
        inputs=("writeup_artifact_gate",),
        required_artifacts=(a("artifacts/proofreading_entry.json", "json"),),
        validators=("paper_draft_available",),
        tool_families=("state_mapper",),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("proofreading_agent"),),
        diagnostic_runtime_mapping={"builder": "build_proofreading_entry_node"},
    ),
    StageContract(
        id="proofreading_agent",
        title="Proofreading",
        kind="agent",
        purpose="Copyedit, tighten style, and produce editorial reports for the paper draft.",
        inputs=("proofreading_entry",),
        required_artifacts=(a("artifacts/copyedit_report.md", legacy=("paper_workspace/copyedit_report.md",)),),
        optional_artifacts=(
            a("artifacts/copyedit_report.tex", "tex", required=False, legacy=("paper_workspace/copyedit_report.tex",)),
            a("artifacts/copyedit_report.pdf", "pdf", required=False, legacy=("paper_workspace/copyedit_report.pdf",)),
        ),
        validators=("copyedit_report_present",),
        tool_families=("llm", "style_editor"),
        budget_policy=AGENT_BUDGET,
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("proofread_gate"),),
        diagnostic_runtime_mapping={"builder": "build_proofreading_node"},
    ),
    StageContract(
        id="proofread_gate",
        title="Proofread Gate",
        kind="gate",
        purpose="Route proofreading failures back to copyediting or forward to review.",
        inputs=("proofreading_agent",),
        required_artifacts=(a("artifacts/proofread_gate_decision.json", "json"),),
        validators=("copyedit_accepted_or_retry_reason",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("proofreading_agent", "loop", condition="copyedit_incomplete"),
            r("reviewer_agent", "route", condition="ready_for_review"),
        ),
        diagnostic_runtime_mapping={"router": "proofread_gate_router"},
    ),
    StageContract(
        id="reviewer_agent",
        title="Reviewer",
        kind="agent",
        purpose="Evaluate the draft like a paper reviewer, identify blockers, and issue a verdict.",
        inputs=("proofread_gate",),
        required_artifacts=(
            a("artifacts/review_report.md", legacy=("paper_workspace/review_report.md",)),
            a("artifacts/review_verdict.json", "json", legacy=("paper_workspace/review_verdict.json",)),
        ),
        optional_artifacts=(
            a("artifacts/review_report.tex", "tex", required=False, legacy=("paper_workspace/review_report.tex",)),
            a("artifacts/review_report.pdf", "pdf", required=False, legacy=("paper_workspace/review_report.pdf",)),
        ),
        validators=("review_verdict_schema", "blockers_actionable"),
        tool_families=("llm", "ensemble_review_optional"),
        budget_policy=HEAVY_AGENT_BUDGET,
        human_pause_policy=("after_reviewer_verdict",),
        failure_policy=DEFAULT_FAILURE,
        allowed_routes=(r("review_gate"),),
        diagnostic_runtime_mapping={"builder": "build_reviewer_node", "ensemble_builder": "build_ensemble_reviewer_node"},
    ),
    StageContract(
        id="review_gate",
        title="Review Gate",
        kind="gate",
        purpose="Loop on review blockers or route to final milestone review.",
        inputs=("reviewer_agent",),
        required_artifacts=(a("artifacts/review_gate_decision.json", "json"),),
        validators=("review_route_present",),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("after_reviewer_verdict", "before_repair_retry_loops"),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("reviewer_agent", "loop", condition="review_needs_retry"),
            r("milestone_review", "route", condition="review_accepted"),
        ),
        diagnostic_runtime_mapping={"router": "review_gate_router"},
    ),
    StageContract(
        id="milestone_review",
        title="Final Review Approval Pause",
        kind="approval",
        purpose="Human checkpoint after review and before final validation/termination.",
        inputs=("review_gate",),
        required_artifacts=(a("artifacts/final_review_approval.json", "json"),),
        validators=("human_decision_recorded_or_autonomous_policy",),
        tool_families=("human_review", "steering_http"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("after_reviewer_verdict",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("validation_gate"),),
        diagnostic_runtime_mapping={"builder": "build_milestone_gate_node", "milestone": "review"},
    ),
    StageContract(
        id="validation_gate",
        title="Final Validation Gate",
        kind="gate",
        purpose="Run final artifact validation and either terminate or route back to repair the missing surface.",
        inputs=("milestone_review",),
        required_artifacts=(a("artifacts/final_validation.json", "json"),),
        validators=("run_validation_gates", "required_artifacts_present"),
        tool_families=("artifact_validator", "router"),
        budget_policy=CONTROL_BUDGET,
        human_pause_policy=("on_every_failure",),
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("writeup_agent", "loop", condition="paper_artifact_failure"),
            r("experiment_track", "loop", condition="experiment_artifact_failure"),
            r("theory_track", "loop", condition="theory_artifact_failure"),
        ),
        diagnostic_runtime_mapping={"router": "validation_router", "terminal": True},
    ),
    StageContract(
        id="iterate_entry",
        title="Iterate Entry",
        kind="control",
        purpose="Seed revision-mode state from an existing paper and feedback directory.",
        inputs=("objective", "prior_paper", "feedback"),
        required_artifacts=(a("artifacts/iteration_context.json", "json"),),
        validators=("iteration_inputs_valid",),
        tool_families=("filesystem", "state_mapper"),
        budget_policy=CONTROL_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(r("persona_council", "revision_route"),),
        diagnostic_runtime_mapping={"mode": "iterate", "node": "iterate_entry"},
        metadata={"graph_scope": "revision"},
    ),
    StageContract(
        id="iterate_router",
        title="Iterate Router",
        kind="router",
        purpose="Classify revision work as writing-only, targeted research, or full rethink.",
        inputs=("persona_council",),
        required_artifacts=(a("artifacts/iteration_route.json", "json"),),
        validators=("iteration_route_present",),
        tool_families=("llm", "router"),
        budget_policy=AGENT_BUDGET,
        failure_policy=GATE_FAILURE,
        allowed_routes=(
            r("resource_preparation_agent", "revision_route", condition="writing_only"),
            r("literature_review_agent", "revision_route", condition="needs_research"),
            r("brainstorm_agent", "revision_route", condition="needs_full_rethink"),
        ),
        diagnostic_runtime_mapping={"mode": "iterate", "node": "iterate_router"},
        metadata={"graph_scope": "revision"},
    ),
)


HISTORICAL_RUNTIME_NODE_IDS = tuple(contract.id for contract in CONTRACTS)
